In [98]:
from sklearn.ensemble import RandomForestClassifier

/home/ravi/miniconda3/envs/fastpy3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

In [99]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import roc_auc_score, make_scorer

In [100]:
import pandas as pd

In [5]:
!ls

forrest_256.csv  Linear.ipynb		sl_learn_ml.ipynb  train.csv  try1.zip
forrest_32.csv	 sample_submission.csv	test.csv	   try1.csv

In [6]:
trn = pd.read_csv('train.csv')

In [7]:
trn.head(2)

   ID_code  target    var_0   var_1  ...  var_196  var_197  var_198  var_199
0  train_0       0   8.9255 -6.7863  ...   7.8784   8.5635  12.7803  -1.0914
1  train_1       0  11.5006 -4.1473  ...   8.1267   8.7889  18.3560   1.9518

[2 rows x 202 columns]

In [8]:
x = trn.drop(['ID_code','target'],axis=1)

In [9]:
x.head(2)

     var_0   var_1    var_2  var_3  ...  var_196  var_197  var_198  var_199
0   8.9255 -6.7863  11.9081  5.093  ...   7.8784   8.5635  12.7803  -1.0914
1  11.5006 -4.1473  13.8588  5.389  ...   8.1267   8.7889  18.3560   1.9518

[2 rows x 200 columns]

In [10]:
y = trn.target

In [116]:
cfr = RandomForestClassifier(n_estimators=9000,n_jobs=-1,max_depth=2)

In [117]:
%time cfr.fit(x[:40000],y[:40000])

CPU times: user 16min 15s, sys: 1.17 s, total: 16min 17s
Wall time: 1min 4s

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=9000, n_jobs=-1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [106]:
s = make_scorer(roc_auc_score)

In [118]:
s(cfr,x[40000:],y[40000:])

0.5

In [33]:
cross_val_score(cfr,x,y)

/home/ravi/miniconda3/envs/fastpy3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)

array([0.89950201, 0.899514  , 0.899514  ])

In [19]:
tst = pd.read_csv('test.csv')

In [20]:
tst.head(2)

  ID_code    var_0   var_1    var_2  ...  var_196  var_197  var_198  var_199
0  test_0  11.0656  7.7798  12.9536  ...   4.3654  10.7200  15.4722  -8.7197
1  test_1   8.5304  1.2543  11.3047  ...  -1.4852   9.8714  19.1293 -20.9760

[2 rows x 201 columns]

In [22]:
tst_x = tst.drop('ID_code',axis=1)

In [34]:
cfr.fit(x,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=5,
            min_weight_fraction_leaf=0.0, n_estimators=256, n_jobs=15,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [35]:
preds = cfr.predict(tst_x)

In [21]:
preds

array([0, 0, 0, ..., 0, 0, 0])

In [126]:
ss = pd.read_csv('sample_submission.csv',index_col = 'ID_code')

In [127]:
ss.head(2)

         target
ID_code
test_0        0
test_1        0

In [128]:
ss.target = preds

In [129]:
ss.to_csv('xgb_99999.csv')

In [57]:
sol = pd.read_csv('forrest_32.csv',index_col='ID_code')

In [58]:
sol.head(2)

         target
ID_code
test_0        0
test_1        0

In [130]:
!kaggle c submit santander-customer-transaction-prediction -f xgb_99999.csv -m "99999 xgb"

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/ravi/.kaggle/kaggle.json'
100%|███████████████████████████████████████| 2.56M/2.56M [00:10<00:00, 245kB/s]
Successfully submitted to Santander Customer Transaction Prediction

In [1]:
from xgboost.sklearn import XGBClassifier

In [2]:
gbcfr = XGBClassifier()

In [11]:
cross_val_score(gbcfr,x,y)

/home/ravi/miniconda3/envs/fastpy3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)

array([0.90118198, 0.90096901, 0.90086401])

In [13]:
import xgboost as xgb

In [14]:
x_ = trn.drop('ID_code',axis=1);
x_.head(2)

   target    var_0   var_1    var_2  ...  var_196  var_197  var_198  var_199
0       0   8.9255 -6.7863  11.9081  ...   7.8784   8.5635  12.7803  -1.0914
1       0  11.5006 -4.1473  13.8588  ...   8.1267   8.7889  18.3560   1.9518

[2 rows x 201 columns]

In [31]:
trn_ = xgb.DMatrix(x,y)

In [32]:
trn_.save_binary('train.buffer')

In [21]:
tst.head(2)

  ID_code    var_0   var_1    var_2  ...  var_196  var_197  var_198  var_199
0  test_0  11.0656  7.7798  12.9536  ...   4.3654  10.7200  15.4722  -8.7197
1  test_1   8.5304  1.2543  11.3047  ...  -1.4852   9.8714  19.1293 -20.9760

[2 rows x 201 columns]

In [23]:
tst_ = xgb.DMatrix(tst_x)

In [24]:
tst_.save_binary('test.buffer')

In [25]:
param = {'max_depth': 2, 'eta': 1, 'silent': 1, 'objective': 'binary:logistic'}
param['nthread'] = 16
param['eval_metric'] = 'auc'

In [39]:
evallist = [ (trn_, 'train')]

In [43]:
num_round = 100

In [47]:
bst = xgb.train(param, trn_, num_round, evallist)

TypeError: train() got an unexpected keyword argument 'n_estimators'

In [46]:
bst.predict(tst_)

array([0.01958389, 0.37266484, 0.0706975 , ..., 0.00259538, 0.0119236 ,
       0.06743246], dtype=float32)

In [37]:
trn_.get_label()

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [120]:
    model = xgb.XGBClassifier(max_depth=2,
                              n_estimators=99999,
                              colsample_bytree=0.3,
                              learning_rate=0.02,
                              objective='binary:logistic', 
                              n_jobs=-1)

In [92]:
#cross_val_score(model,x,y)

In [61]:
x.shape[0]

200000

In [124]:
%time model.fit(x,y)

CPU times: user 20h 14min 3s, sys: 13.5 s, total: 20h 14min 16s
Wall time: 1h 16min 12s

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.3, gamma=0, learning_rate=0.02, max_delta_step=0,
       max_depth=2, min_child_weight=1, missing=None, n_estimators=99999,
       n_jobs=-1, nthread=None, objective='binary:logistic',
       random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
       seed=None, silent=True, subsample=1)

In [94]:
#p = model.predict(x[80000:90000])

In [95]:
s = make_scorer(roc_auc_score)

In [96]:
#s(model,x[80000:],y[80000:])

0.6365416219496781

In [125]:
preds = model.predict(tst_x)